### PR TITLE
befund bundle fixes

### PR DESCRIPTION
**Pull request by dd52**
Remaining validation issues:

**6x Trying to find a string as a code in a code system?**

CodeInvalid : Code 'Expression' from system '' does not exist in valueset 'http://uk-koeln.de/fhir/ValueSet/phenotypes'
Bundle.entry[13].resource[0].component[0].valueString[0]

**Trying to find a code in a non existing valueset**

CodeInvalid : Code '%' from system 'http://unitsofmeasure.org' does not exist in valueset 'http://uk-koeln.de/fhir/ValueSet/0-3+-klassifikation'
Bundle.entry[6].resource[0].component[0].valueQuantity[0]

**Constraint appears to not work properly as there is no MET code in the bundle**

Invariant : Instance failed constraint amplifikation "If Observation concerns MET, ALK or ROS1 then a different VS shall be bound"
Rule: Observation.code.coding.code.where(code = ‘MET’) implies Observation.component.ofType(CodeableConcept).coding.system.where(system = 'http://uk-koeln.de/fhir/ValueSet/nNGM/ergebnis-cish-met').exists() and Observation.code.coding.code.where(code = ‘MET’) implies Observation.component.ofType(CodableConcept).coding.system.where(system = ‘http://uk-koeln.de/fhir/ValueSet/amplification-met’).exists()
Bundle.entry[6].resource[0]

### CODE REVIEW

**Comment by alexzautke** [comment]
@dd52 Re: CodeInvalid : Code 'Expression' from system '' does not exist in valueset 'http://uk-koeln.de/fhir/ValueSet/phenotypes'
Bundle.entry[13].resource[0].component[0].valueString[0]

That's correct Expression is the display value C80488 is the code

**Comment by dd52** [comment]
Issues reduced to one:

Invariant : Instance failed constraint amplifikation "If Observation concerns MET, ALK or ROS1 then a different VS shall be bound"
Rule: Observation.code.coding.code.where(code = ‘MET’) implies Observation.component.ofType(CodeableConcept).coding.system.where(system = 'http://uk-koeln.de/fhir/ValueSet/nNGM/ergebnis-cish-met').exists() and Observation.code.coding.code.where(code = ‘MET’) implies Observation.component.ofType(CodableConcept).coding.system.where(system = ‘http://uk-koeln.de/fhir/ValueSet/amplification-met’).exists()
Bundle.entry[6].resource[0]

**Comment by dd52** [comment]
http://uk-koeln.de/fhir/StructureDefinition/Organization/clinical-site is missing from the package. 

Will take another look at the constraint.

**Comment by ylboerner** [comment]
Can we close this or is this still relevant?

**Pull request closed without merging**
